import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedImage119Widget1.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedGroup18049Widget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedGroup18048Widget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedDoruakWidget2.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/Generated450KMWidget5.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedEllipse128Widget5.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/Generated750KMWidget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedGroup17955Widget6.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/Generated6vrstajelaWidget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedGroup18050Widget.dart';
import 'package:flutterapp/capitalappapp/generateddoruakwidget1/generated/GeneratedGroup18178Widget1.dart';

/* Frame Doručak
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDoruakWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2134.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 2134.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 386.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 825.7142944335938,
                                    child: GeneratedGroup18049Widget(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 1233.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 783.7142944335938,
                                    child: GeneratedGroup18050Widget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.16266666666666665;

                                      final double height =
                                          constraints.maxHeight *
                                              0.01077788191190253;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.128,
                                            y: constraints.maxHeight *
                                                0.46157450796626054,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated450KMWidget5(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.15466666666666667;

                                      final double height =
                                          constraints.maxHeight *
                                              0.01077788191190253;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.128,
                                            y: constraints.maxHeight *
                                                0.8383317713214621,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child: Generated750KMWidget(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 117.56494140625,
                                    top: 13.26025390625,
                                    right: null,
                                    bottom: null,
                                    width: 331.5852355957031,
                                    height: 331.5852355957031,
                                    child: GeneratedImage119Widget1(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 314.0,
                                    right: null,
                                    bottom: null,
                                    width: 172.04237365722656,
                                    height: 26.076797485351562,
                                    child: Generated6vrstajelaWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.10133333333333333;

                                      final double height =
                                          constraints.maxHeight *
                                              0.01780693533270853;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.072,
                                            y: constraints.maxHeight *
                                                0.02014995313964386,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedGroup17955Widget6(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 154.0,
                                    top: -90.0,
                                    right: null,
                                    bottom: null,
                                    width: 318.99993896484375,
                                    height: 318.99993896484375,
                                    child: GeneratedGroup18048Widget(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 269.0,
                                    right: null,
                                    bottom: null,
                                    width: 189.0,
                                    height: 45.0,
                                    child: GeneratedDoruakWidget2(),
                                  ),
                                  Positioned(
                                    left: 284.0,
                                    top: -114.0,
                                    right: null,
                                    bottom: null,
                                    width: 181.0,
                                    height: 181.0,
                                    child: GeneratedEllipse128Widget5(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 102.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 119.0,
                                    child: GeneratedFrame8Widget(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 2060.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedGroup18178Widget1(),
            )
          ]),
    ));
  }
}
