import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedGroup17852Widget8.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedGroup17860Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedGroup18163Widget17.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedGroup17854Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedGroup17853Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedDodaciWidget7.dart';
import 'package:flutterapp/capitalappapp/generatedlahmadunwidget13/generated/GeneratedFairanomesoparadajztijestoWidget.dart';

/* Frame Lahmadžun
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLahmadunWidget13 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 26.0,
                child: GeneratedFairanomesoparadajztijestoWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17853Widget7(),
              ),
              Positioned(
                left: 17.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17852Widget8(),
              ),
              Positioned(
                left: 17.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17854Widget7(),
              ),
              Positioned(
                left: 20.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 23.0,
                child: GeneratedDodaciWidget7(),
              ),
              Positioned(
                left: 99.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 53.0,
                child: GeneratedGroup17860Widget7(),
              ),
              Positioned(
                left: 22.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 329.5980224609375,
                height: 335.59814453125,
                child: GeneratedGroup18163Widget17(),
              )
            ]),
      ),
    ));
  }
}
