import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedEllipse137Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedBarsStatusBariPhoneLightWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedRectangle4168Widget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedImage119Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedGroup18182Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/Generated271046632_500115904965244_6878273998981837278_n440x2641.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedIPhoneXFrameWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedLogo_cbr_20221Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedDobrodoliWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedRestaimg201Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedRectangle4169Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsplashwidget/generated/GeneratedGroup18182Widget1.dart';

/* Frame Splash 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSplashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedLogginWidget'),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 812.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 248, 251, 255),
                  ),
                ),
                Positioned(
                  left: 117.56494140625,
                  top: 13.26025390625,
                  right: null,
                  bottom: null,
                  width: 331.5852355957031,
                  height: 331.5852355957031,
                  child: GeneratedImage119Widget(),
                ),
                Positioned(
                  left: -69.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 506.0,
                  height: 511.0,
                  child:
                      Generated271046632_500115904965244_6878273998981837278_n440x2641(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedRectangle4168Widget1(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedRectangle4169Widget(),
                ),
                Positioned(
                  left: null,
                  top: null,
                  right: null,
                  bottom: 16.0,
                  width: 134.0,
                  height: 5.0,
                  child: TransformHelper.translate(
                      x: 0.50,
                      y: 0.00,
                      z: 0,
                      child: GeneratedRectangleWidget1()),
                ),
                Positioned(
                  left: -1.0,
                  top: -1.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 44.0,
                  child: GeneratedBarsStatusBariPhoneLightWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: GeneratedIPhoneXFrameWidget(),
                ),
                Positioned(
                  left: 340.0,
                  top: 239.0,
                  right: null,
                  bottom: null,
                  width: 272.0,
                  height: 304.0,
                  child: GeneratedEllipse137Widget(),
                ),
                Positioned(
                  left: 57.0,
                  top: 307.0,
                  right: null,
                  bottom: null,
                  width: 256.0,
                  height: 172.0,
                  child: GeneratedLogo_cbr_20221Widget1(),
                ),
                Positioned(
                  left: -115.0,
                  top: -241.0,
                  right: null,
                  bottom: null,
                  width: 518.2359008789062,
                  height: 556.2720336914062,
                  child: GeneratedGroup18182Widget(),
                ),
                Positioned(
                  left: 19.0,
                  top: 596.0,
                  right: null,
                  bottom: null,
                  width: 335.0,
                  height: 79.0,
                  child: GeneratedDobrodoliWidget(),
                ),
                Positioned(
                  left: 77.0,
                  top: 650.0,
                  right: null,
                  bottom: null,
                  width: 212.0,
                  height: 24.0,
                  child: GeneratedRestaimg201Widget(),
                ),
                Positioned(
                  left: 133.0,
                  top: 613.0,
                  right: null,
                  bottom: null,
                  width: 330.04803466796875,
                  height: 354.27203369140625,
                  child: GeneratedGroup18182Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
