import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedRectangle4165Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedGroup17532Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedGroup18160Widget.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedPrijaviseWidget2.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedEllipse126Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/Generated\$167930Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedGroup17955Widget.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedGroup18161Widget.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedNemateprofilRegistrujteseWidget.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedGroup17965Widget.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedEllipse127Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedEllipse128Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedloginwidget/generated/GeneratedZaboravilisteifruWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget1(),
              ),
              Positioned(
                left: 25.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 86.0,
                child: GeneratedGroup17965Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 540.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget1(),
              ),
              Positioned(
                left: 79.0,
                top: 632.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 12.0,
                child: GeneratedNemateprofilRegistrujteseWidget(),
              ),
              Positioned(
                left: 88.0,
                top: 498.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 12.0,
                child: GeneratedZaboravilisteifruWidget(),
              ),
              Positioned(
                left: 26.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 249.0,
                height: 42.0,
                child: GeneratedPrijaviseWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2822176717122396;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10908738199869791,
                        y: constraints.maxHeight * 0.3694581280788177,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated$167930Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07198307291666667,
                        y: constraints.maxHeight * 0.3091133004926108,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18160Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07198307291666667,
                        y: constraints.maxHeight * 0.45935960591133007,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18161Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: -46.0,
                top: -26.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse126Widget1(),
              ),
              Positioned(
                left: -5.0,
                top: -99.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 165.0,
                child: GeneratedEllipse127Widget1(),
              ),
              Positioned(
                left: 298.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 181.0,
                child: GeneratedEllipse128Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.072,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17955Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
