import 'package:flutter/material.dart';

/* Text Upcoming
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUpcomingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Upcoming''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Sofia Pro',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 254, 254, 254),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
