import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup17958Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup18071Widget18.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedRectangle4165Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup17961Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup17852Widget14.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup17960Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup17532Widget10.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedGroup18115Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedaddnewaddresswidget/generated/GeneratedDodajtenovuadresuWidget.dart';

/* Frame Add new address
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAddnewaddressWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.17118226600985223,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17852Widget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.45935960591133007,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17958Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.603448275862069,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17960Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 65.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07198307291666667,
                        y: constraints.maxHeight * 0.31527093596059114,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18115Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.464;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.2613333333333333,
                        y: constraints.maxHeight * 0.07389162561576355,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedDodajtenovuadresuWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.013333333333333334;

                  final double height =
                      constraints.maxHeight * 0.011926021481969674;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.8613333333333333,
                        y: constraints.maxHeight * 0.539019617541083,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17961Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget18(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
