import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedMaskGroupWidget330.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup17532Widget11.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedEllipse129Widget.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedRectangle144Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup17998Widget.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup18154Widget.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup18071Widget19.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedEllipse130Widget.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedRectangle4165Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup18061Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedprofilewidget/generated/GeneratedGroup18153Widget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget7(),
              ),
              Positioned(
                left: 65.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget11(),
              ),
              Positioned(
                left: 119.0,
                top: 130.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 44.0,
                child: GeneratedGroup18061Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9093333333333333;

                  final double height =
                      constraints.maxHeight * 0.5652709359605911;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.048,
                        y: constraints.maxHeight * 0.24876847290640394,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17998Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 287.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedRectangle144Widget2(),
              ),
              Positioned(
                left: 292.333251953125,
                top: 41.16668701171875,
                right: null,
                bottom: null,
                width: 53.33333206176758,
                height: 53.33333206176758,
                child: GeneratedMaskGroupWidget330(),
              ),
              Positioned(
                left: 314.0,
                top: 95.0,
                right: null,
                bottom: null,
                width: 10.0,
                height: 10.0,
                child: GeneratedEllipse129Widget(),
              ),
              Positioned(
                left: 316.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 6.0,
                height: 6.0,
                child: GeneratedEllipse130Widget(),
              ),
              Positioned(
                left: 326.70361328125,
                top: 80.870361328125,
                right: null,
                bottom: null,
                width: 16.0,
                height: 16.0,
                child: GeneratedGroup18153Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget19(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 65.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup18154Widget(),
              )
            ]),
      ),
    ));
  }
}
