import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedframe4widget/generated/GeneratedDefaultWidget.dart';

/* Frame Frame 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 315.0,
      height: 54.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(30.0),
        border: Border.all(
          width: 1.0,
          color: Color.fromARGB(255, 255, 255, 255),
        ),
      ),
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            ClipRRect(
              borderRadius: BorderRadius.circular(30.0),
              child: Container(
                color: Color.fromARGB(53, 255, 255, 255),
              ),
            ),
            Positioned(
              left: 124.0,
              top: 18.5,
              right: null,
              bottom: null,
              width: 72.0,
              height: 22.0,
              child: GeneratedDefaultWidget(),
            )
          ]),
    ));
  }
}
