import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedFlagsWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedRegistracijaWidget.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedEllipse127Widget4.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedEllipse128Widget4.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedGroup17532Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedUnesitesvojbrojtelefonadapotvrditesvojprofilWidget.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedGroup18096Widget.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedEllipse126Widget4.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedGroup17955Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedphoneregistrationwidget/generated/GeneratedRectangle4165Widget4.dart';

/* Frame Phone Registration
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPhoneRegistrationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 375.0,
              height: 812.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 375.0,
                      height: 812.0,
                      child: GeneratedRectangle4165Widget4(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 180.0,
                      right: null,
                      bottom: null,
                      width: 301.0,
                      height: 45.0,
                      child: GeneratedRegistracijaWidget(),
                    ),
                    Positioned(
                      left: -46.0,
                      top: -26.0,
                      right: null,
                      bottom: null,
                      width: 96.0,
                      height: 96.0,
                      child: GeneratedEllipse126Widget4(),
                    ),
                    Positioned(
                      left: -5.0,
                      top: -99.0,
                      right: null,
                      bottom: null,
                      width: 165.0,
                      height: 165.0,
                      child: GeneratedEllipse127Widget4(),
                    ),
                    Positioned(
                      left: 298.0,
                      top: -109.0,
                      right: null,
                      bottom: null,
                      width: 181.0,
                      height: 181.0,
                      child: GeneratedEllipse128Widget4(),
                    ),
                    Positioned(
                      left: 26.0,
                      top: 234.0,
                      right: null,
                      bottom: null,
                      width: 225.0,
                      height: 38.0,
                      child:
                          GeneratedUnesitesvojbrojtelefonadapotvrditesvojprofilWidget(),
                    ),
                    Positioned(
                      left: 65.0,
                      top: 417.0,
                      right: null,
                      bottom: null,
                      width: 248.0,
                      height: 60.0,
                      child: GeneratedGroup17532Widget3(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        final double width =
                            constraints.maxWidth * 0.10133333333333333;

                        final double height =
                            constraints.maxHeight * 0.046798029556650245;

                        return Stack(children: [
                          TransformHelper.translate(
                              x: constraints.maxWidth * 0.072,
                              y: constraints.maxHeight * 0.06280788177339902,
                              z: 0,
                              child: Container(
                                width: width,
                                height: height,
                                child: GeneratedGroup17955Widget3(),
                              ))
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 25.99365234375,
                      top: 301.0,
                      right: null,
                      bottom: null,
                      width: 324.006103515625,
                      height: 65.0,
                      child: GeneratedGroup18096Widget(),
                    )
                  ]),
            ),
            Positioned(
              left: null,
              top: null,
              right: null,
              bottom: null,
              width: 49.0,
              height: 30.0,
              child: TransformHelper.translate(
                  x: -121.00, y: -73.00, z: 0, child: GeneratedFlagsWidget1()),
            )
          ]),
    ));
  }
}
