import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedMaskGroupWidget329.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedMaskGroupWidget328.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedLine85Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedRectangle143Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedRectangle144Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedLogo_cbr_20221Widget4.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedGroup17973Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedCapitalRestaurantWidget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedVector4Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedEllipse136Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedGroup17532Widget9.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedMolimoOcijeniteUsluguDostaveWidget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedGroup17972Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedNapiiterezencijuWidget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedRectangle4137Widget58.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedGroup18068Widget.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedGroup18071Widget17.dart';
import 'package:flutterapp/capitalappapp/generatedratingwidget/generated/GeneratedDemalaBijedia39CapitalTower1sprat71000SarajevoBiHWidget.dart';

/* Frame Rating
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRatingWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 115.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 147.0,
                height: 14.0,
                child: GeneratedGroup17972Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 494.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 168.0,
                child: GeneratedRectangle4137Widget58(),
              ),
              Positioned(
                left: 74.0,
                top: 383.0,
                right: null,
                bottom: null,
                width: 227.47702026367188,
                height: 67.0,
                child: GeneratedGroup17973Widget(),
              ),
              Positioned(
                left: 48.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 161.0,
                height: 17.0,
                child: GeneratedNapiiterezencijuWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 514.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 1.0,
                child: GeneratedLine85Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.7333333333333333;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.136,
                        y: constraints.maxHeight * 0.41625615763546797,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedMolimoOcijeniteUsluguDostaveWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 65.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget9(),
              ),
              Positioned(
                left: 26.0,
                top: 27.0,
                right: null,
                bottom: null,
                width: 323.0001220703125,
                height: 146.0,
                child: GeneratedMaskGroupWidget328(),
              ),
              Positioned(
                left: 136.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 104.0,
                height: 104.0,
                child: GeneratedRectangle144Widget1(),
              ),
              Positioned(
                left: 207.92431640625,
                top: 199.09423828125,
                right: null,
                bottom: null,
                width: 6.792452812194824,
                height: 4.52830171585083,
                child: GeneratedVector4Widget(),
              ),
              Positioned(
                left: 96.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 188.0,
                height: 22.0,
                child: GeneratedCapitalRestaurantWidget(),
              ),
              Positioned(
                left: 59.0,
                top: 266.0,
                right: null,
                bottom: null,
                width: 259.0,
                height: 28.0,
                child:
                    GeneratedDemalaBijedia39CapitalTower1sprat71000SarajevoBiHWidget(),
              ),
              Positioned(
                left: 147.2451171875,
                top: 135.245361328125,
                right: null,
                bottom: null,
                width: 81.50943756103516,
                height: 81.50943756103516,
                child: GeneratedRectangle143Widget3(),
              ),
              Positioned(
                left: 204.45263671875,
                top: 193.452880859375,
                right: null,
                bottom: null,
                width: 21.547170639038086,
                height: 21.547170639038086,
                child: GeneratedEllipse136Widget(),
              ),
              Positioned(
                left: 154.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 69.0,
                height: 69.0,
                child: GeneratedMaskGroupWidget329(),
              ),
              Positioned(
                left: 151.0,
                top: 147.0,
                right: null,
                bottom: null,
                width: 74.0,
                height: 50.0,
                child: GeneratedLogo_cbr_20221Widget4(),
              ),
              Positioned(
                left: 207.64501953125,
                top: 196.64501953125,
                right: null,
                bottom: null,
                width: 15.162823677062988,
                height: 15.162823677062988,
                child: GeneratedGroup18068Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.088,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget17(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
