import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/Generated2vrstajelaWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedFrame8Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedGroup18181Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedGroup18048Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedGroup17955Widget21.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedEllipse128Widget12.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedImage119Widget22.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedSpecialPizzaWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedspecialpizzawidget/generated/GeneratedGroup18178Widget8.dart';

/* Frame Special Pizza
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSpecialPizzaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1095.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1095.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 461.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 515.7142944335938,
                                    child: GeneratedGroup18181Widget6(),
                                  ),
                                  Positioned(
                                    left: 117.56494140625,
                                    top: 13.26025390625,
                                    right: null,
                                    bottom: null,
                                    width: 331.5852355957031,
                                    height: 331.5852355957031,
                                    child: GeneratedImage119Widget22(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.10133333333333333;

                                      final double height =
                                          constraints.maxHeight *
                                              0.034703196347031964;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.072,
                                            y: constraints.maxHeight *
                                                0.039269406392694065,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedGroup17955Widget21(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 154.0,
                                    top: -90.0,
                                    right: null,
                                    bottom: null,
                                    width: 318.99993896484375,
                                    height: 318.99993896484375,
                                    child: GeneratedGroup18048Widget7(),
                                  ),
                                  Positioned(
                                    left: 284.0,
                                    top: -114.0,
                                    right: null,
                                    bottom: null,
                                    width: 181.0,
                                    height: 181.0,
                                    child: GeneratedEllipse128Widget12(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 385.0,
                                    right: null,
                                    bottom: null,
                                    width: 172.04237365722656,
                                    height: 26.076797485351562,
                                    child: Generated2vrstajelaWidget(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 273.0,
                                    right: null,
                                    bottom: null,
                                    width: 250.0,
                                    height: 102.0,
                                    child: GeneratedSpecialPizzaWidget1(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 102.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 119.0,
                                    child: GeneratedFrame8Widget6(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 1021.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedGroup18178Widget8(),
            )
          ]),
    ));
  }
}
