import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedomiljenahranawidget/generated/GeneratedGroup18071Widget20.dart';
import 'package:flutterapp/capitalappapp/generatedomiljenahranawidget/generated/GeneratedFavoritesWidget.dart';
import 'package:flutterapp/capitalappapp/generatedomiljenahranawidget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedomiljenahranawidget/generated/GeneratedGroup18201Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedomiljenahranawidget/generated/GeneratedGroup17911Widget.dart';

/* Frame Omiljena hrana
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedOmiljenahranaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.21333333333333335;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.392,
                        y: constraints.maxHeight * 0.05788177339901478,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedFavoritesWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 26.0,
                top: 107.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 55.0,
                child: GeneratedGroup17911Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.04556650246305419,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget20(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 26.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 323.0,
                height: 608.0,
                child: GeneratedFrame14Widget(),
              ),
              Positioned(
                left: 304.0,
                top: 29.0,
                right: null,
                bottom: null,
                width: 54.0,
                height: 54.0,
                child: GeneratedGroup18201Widget1(),
              )
            ]),
      ),
    ));
  }
}
