import 'package:flutter/material.dart';

/* Rectangle Rectangle 4151
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4151Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 159.96189880371094,
      height: 47.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(23.5),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(64, 211, 209, 216),
            offset: Offset(0.0, 18.0),
            blurRadius: 40.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(23.5),
        child: Container(
          color: Color.fromARGB(255, 254, 114, 76),
        ),
      ),
    ));
  }
}
