import 'package:flutter/material.dart';

/* Rectangle Rectangle 4324
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4324Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 135.0,
      height: 43.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(28.5),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(64, 254, 114, 76),
            offset: Offset(0.0, 20.0),
            blurRadius: 30.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(28.5),
        child: Container(
          color: Color.fromARGB(255, 254, 114, 76),
        ),
      ),
    ));
  }
}
