import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedRectangle4165Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedEllipse128Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedUnesiteverifikacijskikodkojivamjeposlannanekiemailgmail.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedGroup17955Widget1.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedVerifikacijskiKodWidget.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedEllipse127Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedNisamprimiokodMolimopoaljiteponovoWidget.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedGroup18095Widget.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedKeyboardsLightNumericWidget.dart';
import 'package:flutterapp/capitalappapp/generatedvefificationcodewidget/generated/GeneratedEllipse126Widget2.dart';

/* Frame Vefification Code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVefificationCodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 42.0,
                child: GeneratedVerifikacijskiKodWidget(),
              ),
              Positioned(
                left: -46.0,
                top: -26.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse126Widget2(),
              ),
              Positioned(
                left: -5.0,
                top: -99.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 165.0,
                child: GeneratedEllipse127Widget2(),
              ),
              Positioned(
                left: 298.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 181.0,
                child: GeneratedEllipse128Widget2(),
              ),
              Positioned(
                left: 26.0,
                top: 232.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 40.0,
                child:
                    GeneratedUnesiteverifikacijskikodkojivamjeposlannanekiemailgmail(),
              ),
              Positioned(
                left: 27.0,
                top: 301.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 65.0,
                child: GeneratedGroup18095Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 398.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 18.0,
                child: GeneratedNisamprimiokodMolimopoaljiteponovoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.072,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17955Widget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.2660098522167488;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.6822660098522167,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboardsLightNumericWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
