import 'package:flutter/material.dart';

/* Rectangle Male User
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMaleUserWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Visibility(
      visible: false,
      child: Container(
        width: 82.0,
        height: 82.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/830aeec0bd944f04dc1ba9159ea15665c9e0594f.png",
            color: null,
            fit: BoxFit.contain,
            width: 82.0,
            height: 82.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
