import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedNapraviprofilWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedEllipse128Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedEllipse127Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedRectangle4165Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedGroup17532Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedGroup18094Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedVeimateprofilPrijaviseWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/Generated\$167930Widget.dart';
import 'package:flutterapp/capitalappapp/generatedsignupwidget/generated/GeneratedEllipse126Widget.dart';

/* Frame Sign Up
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignUpWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 171, 138, 77),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 698.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 86.0,
                child: GeneratedGroup18094Widget(),
              ),
              Positioned(
                left: 26.0,
                top: 98.0,
                right: null,
                bottom: null,
                width: 274.0,
                height: 44.0,
                child: GeneratedNapraviprofilWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.2105911330049261,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNameWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.2822176717122396;

                  final double height =
                      constraints.maxHeight * 0.03201970443349754;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.10908723958333333,
                        y: constraints.maxHeight * 0.4211822660098522,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: Generated$167930Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 65.0,
                top: 541.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget(),
              ),
              Positioned(
                left: 79.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 220.0,
                height: 12.0,
                child: GeneratedVeimateprofilPrijaviseWidget(),
              ),
              Positioned(
                left: 26.99365234375,
                top: 415.0,
                right: null,
                bottom: null,
                width: 324.006103515625,
                height: 93.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: -46.0,
                top: -26.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse126Widget(),
              ),
              Positioned(
                left: -5.0,
                top: -99.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 165.0,
                child: GeneratedEllipse127Widget(),
              ),
              Positioned(
                left: 298.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 181.0,
                child: GeneratedEllipse128Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07198307291666667,
                        y: constraints.maxHeight * 0.3608374384236453,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedEmailWidget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
