import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedcoverwidget1/generated/GeneratedGroup32931Widget.dart';
import 'package:flutterapp/capitalappapp/generatedcoverwidget1/generated/GeneratedLogo_cbr_20221Widget.dart';

/* Frame Cover
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCoverWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1605.7958984375,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1920.0,
                      height: 960.0,
                      decoration: BoxDecoration(
                        border: Border.all(
                          width: 0.5,
                          color: Color.fromARGB(255, 255, 255, 255),
                        ),
                      ),
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 48, 56, 79),
                              ),
                            ),
                            Positioned(
                              left: 644.7227783203125,
                              top: -646.0,
                              right: null,
                              bottom: null,
                              width: 1414.1414794921875,
                              height: 2251.7958984375,
                              child: GeneratedGroup32931Widget(),
                            ),
                            Positioned(
                              left: 124.0,
                              top: 307.0,
                              right: null,
                              bottom: null,
                              width: 516.0,
                              height: 346.0,
                              child: GeneratedLogo_cbr_20221Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
