import 'package:flutter/material.dart';

/* Rectangle Rectangle 139
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle139Widget14 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 248.0,
      height: 60.0,
      decoration: BoxDecoration(
        borderRadius: BorderRadius.circular(28.5),
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(40, 122, 128, 190),
            offset: Offset(0.0, 10.0),
            blurRadius: 40.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.circular(28.5),
        child: Container(
          color: Color.fromARGB(255, 254, 114, 76),
        ),
      ),
    ));
  }
}
