import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup17776Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedRecenzijeWidget12.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup17775Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup17700Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup17777Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup17774Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewswidget/generated/GeneratedGroup18071Widget16.dart';

/* Frame Reviews
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.22133333333333333;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.39466666666666667,
                        y: constraints.maxHeight * 0.07389162561576355,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRecenzijeWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 25.0,
                top: 190.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 139.0,
                child: GeneratedGroup17774Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 205.0,
                child: GeneratedGroup17775Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 139.0,
                child: GeneratedGroup17776Widget(),
              ),
              Positioned(
                left: 25.0,
                top: 763.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 139.0,
                child: GeneratedGroup17777Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8666666666666667;

                  final double height =
                      constraints.maxHeight * 0.06280788177339902;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06666666666666667,
                        y: constraints.maxHeight * 0.12807881773399016,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17700Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget16(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
