import 'package:flutter/material.dart';

/* UndefinedNode Frame 11
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame11Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
