import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedGroup17970Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedKakvajebilaVaaposljednjenarudbaizCapitalRestaurantWidge.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedGroup17969Widget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedLine60Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedGroup18071Widget12.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedNapiiteWidget.dart';
import 'package:flutterapp/capitalappapp/generatedreviewrestoranwidget/generated/GeneratedGroup17532Widget6.dart';

/* Frame Review Restoran
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedReviewRestoranWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 26.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 74.0,
                child:
                    GeneratedKakvajebilaVaaposljednjenarudbaizCapitalRestaurantWidge(),
              ),
              Positioned(
                left: 73.9541015625,
                top: 400.0,
                right: null,
                bottom: null,
                width: 227.47702026367188,
                height: 67.0,
                child: GeneratedGroup17969Widget(),
              ),
              Positioned(
                left: 65.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget6(),
              ),
              Positioned(
                left: 26.0,
                top: 533.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 21.0,
                child: GeneratedNapiiteWidget(),
              ),
              Positioned(
                left: 27.0,
                top: 563.0,
                right: null,
                bottom: null,
                width: 321.0,
                height: 1.0,
                child: GeneratedLine60Widget(),
              ),
              Positioned(
                left: 147.608642578125,
                top: 119.0,
                right: null,
                bottom: null,
                width: 79.39129638671875,
                height: 79.39129638671875,
                child: GeneratedGroup17970Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07066666666666667,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget12(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
