import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedKorpaWidget12.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup18184Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup18157Widget.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup18158Widget.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup17889Widget.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup17883Widget.dart';
import 'package:flutterapp/capitalappapp/generatedkorpawidget11/generated/GeneratedGroup17532Widget4.dart';

/* Frame Korpa
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedKorpaWidget11 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.14666666666666667;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.432,
                        y: constraints.maxHeight * 0.07512315270935961,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKorpaWidget12(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18184Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 64.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 57.0,
                child: GeneratedGroup17532Widget4(),
              ),
              Positioned(
                left: 22.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 121.0,
                child: GeneratedGroup18157Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 369.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 60.0,
                child: GeneratedGroup17883Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 144.0,
                right: null,
                bottom: null,
                width: 328.0000915527344,
                height: 83.28031158447266,
                child: GeneratedGroup18158Widget(),
              ),
              Positioned(
                left: 22.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 326.0000915527344,
                height: 83.28031158447266,
                child: GeneratedGroup17889Widget(),
              )
            ]),
      ),
    ));
  }
}
