import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedgroup17963widget2/generated/GeneratedRectangle4147Widget.dart';
import 'package:flutterapp/capitalappapp/generatedgroup17963widget2/generated/GeneratedSkipWidget.dart';

/* Group Group 17963
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup17963Widget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 55.0,
      height: 32.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 55.0,
              height: 32.0,
              child: GeneratedRectangle4147Widget(),
            ),
            Positioned(
              left: 14.0,
              top: 10.0,
              right: null,
              bottom: null,
              width: 32.0,
              height: 16.0,
              child: GeneratedSkipWidget(),
            )
          ]),
    ));
  }
}
