import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedstyleguidewidget1/generated/GeneratedGroup33952Widget.dart';
import 'package:flutterapp/capitalappapp/generatedstyleguidewidget1/generated/GeneratedStyleGuideWidget2.dart';
import 'package:flutterapp/capitalappapp/generatedstyleguidewidget1/generated/GeneratedRectangle4168Widget2.dart';

/* Frame Style Guide
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStyleGuideWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 2000.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 1418.0,
                      height: 2000.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: null,
                              bottom: null,
                              width: 1920.0,
                              height: 126.0,
                              child: GeneratedRectangle4168Widget2(),
                            ),
                            Positioned(
                              left: 83.0,
                              top: 35.0,
                              right: null,
                              bottom: null,
                              width: 265.0,
                              height: 68.0,
                              child: GeneratedStyleGuideWidget2(),
                            ),
                            Positioned(
                              left: 78.0,
                              top: 169.0,
                              right: null,
                              bottom: null,
                              width: 1245.0,
                              height: 1661.0,
                              child: GeneratedGroup33952Widget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
