import 'package:flutter/material.dart';

/* Rectangle Rectangle 4322
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRectangle4322Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 131.0,
      height: 118.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          color: Color.fromARGB(255, 139, 112, 62),
        ),
      ),
    ));
  }
}
