import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedGroup18181Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedFrame8Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/Generated3vrstajelaWidget.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedEllipse128Widget8.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedorbeiSupeWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedGroup18048Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedGroup17955Widget14.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedImage119Widget10.dart';
import 'package:flutterapp/capitalappapp/generatedorbeisupewidget/generated/GeneratedGroup18178Widget4.dart';

/* Frame Čorbe i Supe
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedorbeiSupeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 1355.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 1355.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 447.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 783.7142944335938,
                                    child: GeneratedGroup18181Widget2(),
                                  ),
                                  Positioned(
                                    left: 117.56494140625,
                                    top: 13.26025390625,
                                    right: null,
                                    bottom: null,
                                    width: 331.5852355957031,
                                    height: 331.5852355957031,
                                    child: GeneratedImage119Widget10(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 371.0,
                                    right: null,
                                    bottom: null,
                                    width: 172.04237365722656,
                                    height: 26.076797485351562,
                                    child: Generated3vrstajelaWidget(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.10133333333333333;

                                      final double height =
                                          constraints.maxHeight *
                                              0.028044280442804426;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.072,
                                            y: constraints.maxHeight *
                                                0.03173431734317343,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedGroup17955Widget14(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 154.0,
                                    top: -90.0,
                                    right: null,
                                    bottom: null,
                                    width: 318.99993896484375,
                                    height: 318.99993896484375,
                                    child: GeneratedGroup18048Widget3(),
                                  ),
                                  Positioned(
                                    left: 284.0,
                                    top: -114.0,
                                    right: null,
                                    bottom: null,
                                    width: 181.0,
                                    height: 181.0,
                                    child: GeneratedEllipse128Widget8(),
                                  ),
                                  Positioned(
                                    left: 26.0,
                                    top: 273.0,
                                    right: null,
                                    bottom: null,
                                    width: 247.0,
                                    height: 99.0,
                                    child: GeneratedorbeiSupeWidget1(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 102.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 119.0,
                                    child: GeneratedFrame8Widget2(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 1281.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedGroup18178Widget4(),
            )
          ]),
    ));
  }
}
