import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedGroup17955Widget2.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedEllipse128Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedEllipse127Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedResetLozinkeWidget.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedKeyboardsLightNumericWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedEllipse126Widget3.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedRectangle4165Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedUnesitesvojuadresuepotedazatraiteresetovanjelozinkeWidg.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedGroup18107Widget.dart';
import 'package:flutterapp/capitalappapp/generatedressetpasswordwidget/generated/GeneratedGroup17532Widget2.dart';

/* Frame Resset Password
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRessetPasswordWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangle4165Widget3(),
              ),
              Positioned(
                left: 26.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 298.0,
                height: 42.0,
                child: GeneratedResetLozinkeWidget(),
              ),
              Positioned(
                left: -46.0,
                top: -26.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 96.0,
                child: GeneratedEllipse126Widget3(),
              ),
              Positioned(
                left: -5.0,
                top: -99.0,
                right: null,
                bottom: null,
                width: 165.0,
                height: 165.0,
                child: GeneratedEllipse127Widget3(),
              ),
              Positioned(
                left: 298.0,
                top: -109.0,
                right: null,
                bottom: null,
                width: 181.0,
                height: 181.0,
                child: GeneratedEllipse128Widget3(),
              ),
              Positioned(
                left: 26.0,
                top: 234.0,
                right: null,
                bottom: null,
                width: 238.0,
                height: 31.0,
                child:
                    GeneratedUnesitesvojuadresuepotedazatraiteresetovanjelozinkeWidg(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.08004926108374384;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06931640625,
                        y: constraints.maxHeight * 0.3706896551724138,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18107Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 65.0,
                top: 417.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.072,
                        y: constraints.maxHeight * 0.06280788177339902,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17955Widget2(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth;

                  final double height =
                      constraints.maxHeight * 0.2660098522167488;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: 0,
                        y: constraints.maxHeight * 0.6810344827586207,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedKeyboardsLightNumericWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
