import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedGroup18181Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedEllipse128Widget13.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedPastaiRiotoWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedFrame8Widget7.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedGroup18178Widget9.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedImage119Widget25.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedGroup18048Widget8.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/GeneratedGroup17955Widget22.dart';
import 'package:flutterapp/capitalappapp/generatedpastairiotowidget/generated/Generated7vrstajelaWidget.dart';

/* Frame Pasta i Rižoto
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPastaiRiotoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              return SingleChildScrollView(
                scrollDirection: Axis.vertical,
                child: Container(
                    height: 2431.0,
                    child: Stack(children: [
                      Container(
                          width: constraints.maxWidth,
                          child: Container(
                            width: 375.0,
                            height: 2431.0,
                            child: Stack(
                                fit: StackFit.expand,
                                alignment: Alignment.center,
                                overflow: Overflow.visible,
                                children: [
                                  ClipRRect(
                                    borderRadius: BorderRadius.zero,
                                    child: Container(
                                      color: Color.fromARGB(255, 248, 251, 255),
                                    ),
                                  ),
                                  Positioned(
                                    left: 117.56494140625,
                                    top: 13.26025390625,
                                    right: null,
                                    bottom: null,
                                    width: 331.5852355957031,
                                    height: 331.5852355957031,
                                    child: GeneratedImage119Widget25(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 0.0,
                                    right: 0.0,
                                    bottom: 0.0,
                                    width: null,
                                    height: null,
                                    child: LayoutBuilder(builder:
                                        (BuildContext context,
                                            BoxConstraints constraints) {
                                      final double width =
                                          constraints.maxWidth *
                                              0.10133333333333333;

                                      final double height =
                                          constraints.maxHeight *
                                              0.01563142739613328;

                                      return Stack(children: [
                                        TransformHelper.translate(
                                            x: constraints.maxWidth * 0.072,
                                            y: constraints.maxHeight *
                                                0.017688194158782394,
                                            z: 0,
                                            child: Container(
                                              width: width,
                                              height: height,
                                              child:
                                                  GeneratedGroup17955Widget22(),
                                            ))
                                      ]);
                                    }),
                                  ),
                                  Positioned(
                                    left: 154.0,
                                    top: -90.0,
                                    right: null,
                                    bottom: null,
                                    width: 318.99993896484375,
                                    height: 318.99993896484375,
                                    child: GeneratedGroup18048Widget8(),
                                  ),
                                  Positioned(
                                    left: 284.0,
                                    top: -114.0,
                                    right: null,
                                    bottom: null,
                                    width: 181.0,
                                    height: 181.0,
                                    child: GeneratedEllipse128Widget13(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 385.0,
                                    right: null,
                                    bottom: null,
                                    width: 172.04237365722656,
                                    height: 26.076797485351562,
                                    child: Generated7vrstajelaWidget(),
                                  ),
                                  Positioned(
                                    left: 25.0,
                                    top: 273.0,
                                    right: null,
                                    bottom: null,
                                    width: 247.0,
                                    height: 99.0,
                                    child: GeneratedPastaiRiotoWidget1(),
                                  ),
                                  Positioned(
                                    left: 27.0,
                                    top: 464.0,
                                    right: null,
                                    bottom: null,
                                    width: 323.0,
                                    height: 1855.7142333984375,
                                    child: GeneratedGroup18181Widget7(),
                                  ),
                                  Positioned(
                                    left: 0.0,
                                    top: 102.0,
                                    right: null,
                                    bottom: null,
                                    width: 375.0,
                                    height: 119.0,
                                    child: GeneratedFrame8Widget7(),
                                  )
                                ]),
                          ))
                    ])),
              );
            }),
            Positioned(
              left: 0.0,
              top: 2357.0,
              right: null,
              bottom: null,
              width: 375.0,
              height: 74.0,
              child: GeneratedGroup18178Widget9(),
            )
          ]),
    ));
  }
}
