import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedGroup17853Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedGroup17854Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedGroup17860Widget6.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedGroup18163Widget16.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedPohovanapiletinakuhanojajekupuskorijandermladilukpeenib.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedGroup17852Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedpileasusamsalatawidget1/generated/GeneratedDodaciWidget6.dart';

/* Frame Pileća Susam Salata
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPileaSusamSalataWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 401.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 74.0,
                child:
                    GeneratedPohovanapiletinakuhanojajekupuskorijandermladilukpeenib(),
              ),
              Positioned(
                left: 17.0,
                top: 531.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17853Widget6(),
              ),
              Positioned(
                left: 17.0,
                top: 580.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17852Widget7(),
              ),
              Positioned(
                left: 17.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 334.25,
                height: 39.1741943359375,
                child: GeneratedGroup17854Widget6(),
              ),
              Positioned(
                left: 20.0,
                top: 503.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 23.0,
                child: GeneratedDodaciWidget6(),
              ),
              Positioned(
                left: 99.0,
                top: 727.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 53.0,
                child: GeneratedGroup17860Widget6(),
              ),
              Positioned(
                left: 22.0,
                top: 43.0,
                right: null,
                bottom: null,
                width: 329.5980224609375,
                height: 335.59814453125,
                child: GeneratedGroup18163Widget16(),
              )
            ]),
      ),
    ));
  }
}
