import 'package:flutter/material.dart';

/* UndefinedNode Component 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedComponent2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
