import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18202Widget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18201Widget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup17532Widget8.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18061Widget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18204Widget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18203Widget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup17852Widget13.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedNovaRezervacijaWidget.dart';
import 'package:flutterapp/capitalappapp/generatedrezervacijawidget/generated/GeneratedGroup18071Widget15.dart';

/* Frame Rezervacija
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRezervacijaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07066666666666667,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget15(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.38666666666666666;

                  final double height =
                      constraints.maxHeight * 0.024630541871921183;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.312,
                        y: constraints.maxHeight * 0.07389162561576355,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNovaRezervacijaWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 53.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget8(),
              ),
              Positioned(
                left: 108.0,
                top: 176.0,
                right: null,
                bottom: null,
                width: 140.0,
                height: 20.0,
                child: GeneratedGroup18061Widget(),
              ),
              Positioned(
                left: 146.0,
                top: 104.0,
                right: null,
                bottom: null,
                width: 64.0,
                height: 64.0,
                child: GeneratedGroup18201Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.2733990147783251,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup17852Widget13(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.4100985221674877,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18202Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8640162760416666;

                  final double height =
                      constraints.maxHeight * 0.1145320197044335;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.5467980295566502,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18203Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.864;

                  final double height =
                      constraints.maxHeight * 0.1539408866995074;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.06933333333333333,
                        y: constraints.maxHeight * 0.6834975369458128,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18204Widget(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
