import 'package:flutter/material.dart';

/* Text Track Order
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedTrackOrderWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Text(
      '''Track Order''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 15.0,
        fontFamily: 'Sofia Pro',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 255, 255, 255),

        /* letterSpacing: 0.0, */
      ),
    ));
  }
}
