import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedgroup17860widget12/generated/GeneratedAddtocartWidget.dart';
import 'package:flutterapp/capitalappapp/generatedgroup17860widget12/generated/GeneratedGroup17858Widget12.dart';

/* Group Group 17860
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup17860Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 167.0,
      height: 53.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 167.0,
              height: 53.0,
              child: GeneratedGroup17858Widget12(),
            ),
            Positioned(
              left: 59.0,
              top: 19.0,
              right: null,
              bottom: null,
              width: 88.0,
              height: 17.0,
              child: GeneratedAddtocartWidget(),
            )
          ]),
    ));
  }
}
