import 'package:flutter/material.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedGroup17532Widget7.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedGroup18071Widget14.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedPlaanjeWidget1.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedGroup50Widget.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedGroup52Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/capitalappapp/generatedplaanjewidget/generated/GeneratedGroup51Widget.dart';

/* Frame Plaćanje
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPlaanjeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 248, 251, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.10133333333333333;

                  final double height =
                      constraints.maxHeight * 0.046798029556650245;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.07066666666666667,
                        y: constraints.maxHeight * 0.06157635467980296,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedGroup18071Widget14(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.20266666666666666;

                  final double height =
                      constraints.maxHeight * 0.02832512315270936;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.408,
                        y: constraints.maxHeight * 0.07389162561576355,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedPlaanjeWidget1(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 40.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 231.0,
                child: GeneratedGroup50Widget(),
              ),
              Positioned(
                left: 40.0,
                top: 420.0,
                right: null,
                bottom: null,
                width: 297.9642028808594,
                height: 186.0,
                child: GeneratedGroup52Widget(),
              ),
              Positioned(
                left: 34.0,
                top: 641.0,
                right: null,
                bottom: null,
                width: 304.0,
                height: 22.0,
                child: GeneratedGroup51Widget(),
              ),
              Positioned(
                left: 53.0,
                top: 719.0,
                right: null,
                bottom: null,
                width: 248.0,
                height: 60.0,
                child: GeneratedGroup17532Widget7(),
              )
            ]),
      ),
    ));
  }
}
